### ISSUE TITLE
没有这个jar包哎--[WARNING] The POM for com.yudianbank.plugin:api-abstractor:jar:1.1.3-RELEASE is missing, no dependency information available

### ISSUE THREAD

**Issue by jinyan2049** [kekingcn/kkbinlog#17]
[WARNING] The POM for com.yudianbank.plugin:api-abstractor:jar:1.1.3-RELEASE is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] bin-log-distributor 0.5.0-SNAPSHOT ................. SUCCESS [  0.107 s]
[INFO] bin-log-distributor-param .......................... SUCCESS [  1.138 s]
[INFO] bin-log-distributor-pub-redis ...................... SUCCESS [  0.157 s]
[INFO] bin-log-distributor-pub-rabbitmq ................... SUCCESS [  0.283 s]
[INFO] bin-log-distributor-pub-kafka ...................... SUCCESS [  0.184 s]
[INFO] bin-log-distributor-pub ............................ SUCCESS [  0.134 s]
[INFO] bin-log-distributor-app ............................ FAILURE [  0.014 s]
[INFO] bin-log-distributor-client ......................... SKIPPED
[INFO] bin-log-distributor-client-redis ................... SKIPPED
[INFO] bin-log-distributor-client-redis ................... SKIPPED
[INFO] bin-log-distributor-example-redis .................. SKIPPED
[INFO] bin-log-distributor-example-rabbitmq ............... SKIPPED
[INFO] bin-log-distributor-example-multi-datasource 0.5.0-SNAPSHOT SKIPPED

**Comment by klboke** [comment]
可以了，有个内部插件忘记移除了，你拉下最新的代码在编译试试
